import * as schema from '@life-os/database';
import { AppSchema } from '@powersync/react-native';

// PowerSync schema for mobile offline sync
export const powersyncSchema = new AppSchema({
  app_users: {
    id: schema.appUsers.id,
    supabase_user_id: schema.appUsers.supabaseUserId,
    email: schema.appUsers.email,
    full_name: schema.appUsers.fullName,
    created_at: schema.appUsers.createdAt,
    updated_at: schema.appUsers.updatedAt,
  },
  workspaces: {
    id: schema.workspaces.id,
    name: schema.workspaces.name,
    owner_id: schema.workspaces.ownerId,
    created_at: schema.workspaces.createdAt,
    updated_at: schema.workspaces.updatedAt,
  },
  workspace_memberships: {
    id: schema.workspaceMemberships.id,
    workspace_id: schema.workspaceMemberships.workspaceId,
    user_id: schema.workspaceMemberships.userId,
    role: schema.workspaceMemberships.role,
    created_at: schema.workspaceMemberships.createdAt,
  },
  projects: {
    id: schema.projects.id,
    workspace_id: schema.projects.workspaceId,
    name: schema.projects.name,
    description: schema.projects.description,
    color: schema.projects.color,
    icon: schema.projects.icon,
    status: schema.projects.status,
    created_at: schema.projects.createdAt,
    updated_at: schema.projects.updatedAt,
  },
  tasks: {
    id: schema.tasks.id,
    workspace_id: schema.tasks.workspaceId,
    project_id: schema.tasks.projectId,
    parent_id: schema.tasks.parentId,
    title: schema.tasks.title,
    description: schema.tasks.description,
    status: schema.tasks.status,
    priority: schema.tasks.priority,
    due_date: schema.tasks.dueDate,
    due_time: schema.tasks.dueTime,
    estimated_duration: schema.tasks.estimatedDuration,
    completed_at: schema.tasks.completedAt,
    calendar_event_id: schema.tasks.calendarEventId,
    recurrence_rule: schema.tasks.recurrenceRule,
    recurrence_id: schema.tasks.recurrenceId,
    energy_level: schema.tasks.energyLevel,
    context_tags: schema.tasks.contextTags,
    is_milestone: schema.tasks.isMilestone,
    created_at: schema.tasks.createdAt,
    updated_at: schema.tasks.updatedAt,
  },
  task_dependencies: {
    id: schema.taskDependencies.id,
    task_id: schema.taskDependencies.taskId,
    depends_on_task_id: schema.taskDependencies.dependsOnTaskId,
    type: schema.taskDependencies.type,
    created_at: schema.taskDependencies.createdAt,
  },
  task_notes: {
    id: schema.taskNotes.id,
    task_id: schema.taskNotes.taskId,
    content: schema.taskNotes.content,
    created_at: schema.taskNotes.createdAt,
    updated_at: schema.taskNotes.updatedAt,
  },
  task_assignees: {
    id: schema.taskAssignees.id,
    task_id: schema.taskAssignees.taskId,
    user_id: schema.taskAssignees.userId,
    assigned_by: schema.taskAssignees.assignedBy,
    assigned_at: schema.taskAssignees.assignedAt,
    is_primary: schema.taskAssignees.isPrimary,
  },
  task_comments: {
    id: schema.taskComments.id,
    task_id: schema.taskComments.taskId,
    user_id: schema.taskComments.userId,
    content: schema.taskComments.content,
    parent_id: schema.taskComments.parentId,
    mentions: schema.taskComments.mentions,
    created_at: schema.taskComments.createdAt,
    updated_at: schema.taskComments.updatedAt,
  },
  task_attachments: {
    id: schema.taskAttachments.id,
    task_id: schema.taskAttachments.taskId,
    uploaded_by: schema.taskAttachments.uploadedBy,
    file_name: schema.taskAttachments.fileName,
    file_type: schema.taskAttachments.fileType,
    file_size: schema.taskAttachments.fileSize,
    storage_path: schema.taskAttachments.storagePath,
    storage_bucket: schema.taskAttachments.storageBucket,
    metadata: schema.taskAttachments.metadata,
    created_at: schema.taskAttachments.createdAt,
  },
  time_entries: {
    id: schema.timeEntries.id,
    task_id: schema.timeEntries.taskId,
    user_id: schema.timeEntries.userId,
    description: schema.timeEntries.description,
    started_at: schema.timeEntries.startedAt,
    stopped_at: schema.timeEntries.stoppedAt,
    duration: schema.timeEntries.duration,
    is_billable: schema.timeEntries.isBillable,
    billable_rate: schema.timeEntries.billableRate,
    metadata: schema.timeEntries.metadata,
    created_at: schema.timeEntries.createdAt,
    updated_at: schema.timeEntries.updatedAt,
  },
  calendars: {
    id: schema.calendars.id,
    workspace_id: schema.calendars.workspaceId,
    name: schema.calendars.name,
    description: schema.calendars.description,
    color: schema.calendars.color,
    is_default: schema.calendars.isDefault,
    provider: schema.calendars.provider,
    provider_calendar_id: schema.calendars.providerCalendarId,
    created_at: schema.calendars.createdAt,
    updated_at: schema.calendars.updatedAt,
  },
  events: {
    id: schema.events.id,
    workspace_id: schema.events.workspaceId,
    calendar_id: schema.events.calendarId,
    title: schema.events.title,
    description: schema.events.description,
    location: schema.events.location,
    is_all_day: schema.events.isAllDay,
    start: schema.events.start,
    end: schema.events.end,
    timezone: schema.events.timezone,
    recurrence_rule: schema.events.recurrenceRule,
    recurrence_id: schema.events.recurrenceId,
    provider_event_id: schema.events.providerEventId,
    task_id: schema.events.taskId,
    created_at: schema.events.createdAt,
    updated_at: schema.events.updatedAt,
  },
  event_attendees: {
    id: schema.eventAttendees.id,
    event_id: schema.eventAttendees.eventId,
    email: schema.eventAttendees.email,
    name: schema.eventAttendees.name,
    status: schema.eventAttendees.status,
    is_organizer: schema.eventAttendees.isOrganizer,
    created_at: schema.eventAttendees.createdAt,
  },
  scheduling_links: {
    id: schema.schedulingLinks.id,
    workspace_id: schema.schedulingLinks.workspaceId,
    user_id: schema.schedulingLinks.userId,
    name: schema.schedulingLinks.name,
    slug: schema.schedulingLinks.slug,
    description: schema.schedulingLinks.description,
    calendar_id: schema.schedulingLinks.calendarId,
    event_duration: schema.schedulingLinks.eventDuration,
    buffer_before: schema.schedulingLinks.bufferBefore,
    buffer_after: schema.schedulingLinks.bufferAfter,
    min_booking_notice: schema.schedulingLinks.minBookingNotice,
    max_booking_notice: schema.schedulingLinks.maxBookingNotice,
    availability_start: schema.schedulingLinks.availabilityStart,
    availability_end: schema.schedulingLinks.availabilityEnd,
    available_days: schema.schedulingLinks.availableDays,
    is_active: schema.schedulingLinks.isActive,
    requires_approval: schema.schedulingLinks.requiresApproval,
    max_daily_bookings: schema.schedulingLinks.maxDailyBookings,
    created_at: schema.schedulingLinks.createdAt,
    updated_at: schema.schedulingLinks.updatedAt,
  },
});

export default powersyncSchema;
