import { AppSchema } from '@powersync/react-native';
import * as schema from '@life-os/database';

// PowerSync schema for mobile offline sync
export const powersyncSchema = new AppSchema({
  app_users: {
    id: schema.appUsers.id,
    supabase_user_id: schema.appUsers.supabaseUserId,
    email: schema.appUsers.email,
    full_name: schema.appUsers.fullName,
    created_at: schema.appUsers.createdAt,
    updated_at: schema.appUsers.updatedAt,
  },
  workspaces: {
    id: schema.workspaces.id,
    name: schema.workspaces.name,
    owner_id: schema.workspaces.ownerId,
    created_at: schema.workspaces.createdAt,
    updated_at: schema.workspaces.updatedAt,
  },
  workspace_memberships: {
    id: schema.workspaceMemberships.id,
    workspace_id: schema.workspaceMemberships.workspaceId,
    user_id: schema.workspaceMemberships.userId,
    role: schema.workspaceMemberships.role,
    created_at: schema.workspaceMemberships.createdAt,
  },
  projects: {
    id: schema.projects.id,
    workspace_id: schema.projects.workspaceId,
    name: schema.projects.name,
    description: schema.projects.description,
    color: schema.projects.color,
    icon: schema.projects.icon,
    status: schema.projects.status,
    created_at: schema.projects.createdAt,
    updated_at: schema.projects.updatedAt,
  },
  tasks: {
    id: schema.tasks.id,
    workspace_id: schema.tasks.workspaceId,
    project_id: schema.tasks.projectId,
    title: schema.tasks.title,
    description: schema.tasks.description,
    status: schema.tasks.status,
    priority: schema.tasks.priority,
    due_date: schema.tasks.dueDate,
    due_time: schema.tasks.dueTime,
    estimated_duration: schema.tasks.estimatedDuration,
    completed_at: schema.tasks.completedAt,
    calendar_event_id: schema.tasks.calendarEventId,
    created_at: schema.tasks.createdAt,
    updated_at: schema.tasks.updatedAt,
  },
  calendars: {
    id: schema.calendars.id,
    workspace_id: schema.calendars.workspaceId,
    name: schema.calendars.name,
    description: schema.calendars.description,
    color: schema.calendars.color,
    is_default: schema.calendars.isDefault,
    provider: schema.calendars.provider,
    provider_calendar_id: schema.calendars.providerCalendarId,
    created_at: schema.calendars.createdAt,
    updated_at: schema.calendars.updatedAt,
  },
  events: {
    id: schema.events.id,
    workspace_id: schema.events.workspaceId,
    calendar_id: schema.events.calendarId,
    title: schema.events.title,
    description: schema.events.description,
    location: schema.events.location,
    is_all_day: schema.events.isAllDay,
    start: schema.events.start,
    end: schema.events.end,
    timezone: schema.events.timezone,
    recurrence_rule: schema.events.recurrenceRule,
    recurrence_id: schema.events.recurrenceId,
    provider_event_id: schema.events.providerEventId,
    task_id: schema.events.taskId,
    created_at: schema.events.createdAt,
    updated_at: schema.events.updatedAt,
  },
});

export default powersyncSchema;
